const messages = {
  userCreated: 'Account created successfully',
  invalidFirstNameValue: 'Please provide a valid firstName',
  invalidLastNameValue: 'Please provide a valid lastName',
  invalidEmailValue: 'Please provide a valid email',
  invalidPhoneNumberValue: 'Please provide a valid phoneNumber',
  invalidPasswordValue: 'Please provide a valid password',
  invalidUserType: 'The userType is invalid',
  invalidLinkedIn: 'Please provide a valid link',
  invalidGithubUsername: 'Please provide a valid githubUsername',
  duplicateUserAccount: 'This account already exist',
  successfulLogin: 'LoggedIn successfully',
  userNotFound: 'No account associated to this credentials',
  incorrectPassword: 'Incorrect password',
  inactiveAccount: 'Account is not activated',
  postJob: 'Job posted successfully',
  unauthorizedAccess: 'Unauthorized access',
  invalidToken: 'Invalid token',
  invalidTitle: 'Please provide a valid title',
  invalidPrice: 'Please provide a valid price',
  invalidYearsOfExperience: 'Please provide a valid years of experience value',
  invalidJobType: 'Please provide a valid job type',
  invalidStartDate: 'Please provide valid start date',
  invalidEndDate: 'Please provide valid end date',
  invalidJobDescription: 'Please provide valid Job description',
  jobDuplication: 'You can not create the same project twice',
  allJobs: 'all jobs',
  invalidJobStatus: 'Please provide a valid job status value',
  jobDetails: 'Job details',
  invalidId: 'Please provide a valid id',
  jobNotFound: 'Job not Found',
  jobUpdated: 'Job updated',
  duplicateStatus: 'This Job already has that status',
  appliedSuccessfully: 'Applied successfully',
  notDeveloper: 'Only developers can apply for jobs',
  jobNotOpened: 'This job is not available',
  duplicateApplication: 'Application already exist',
  applicationApproved: 'Application approved successfully',
  applicationNotFound: 'Application not Found',
  allApplications: 'All applications for this job',
  applicationFound: 'Application found',
  jobDeleted: 'Job deleted successfully',
  notificationStatusUpdated: 'Notification status updated successfully',
  githubUserNotFound: 'Github user not found',
  gitHubUserFound: 'Github user data',
  profileData: 'Profile Data',
  notEligible: 'You dont qualify for this job',
};
export default messages;
